export const playlists = [
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
    "Running playlist",
];